

# 포트 바꿀 시에
server:
  port: 8000

spring:
  application:
    name: virtudy

  # local profiles 로 빌드하기
  profiles:
    active: local

  data:
    redis:
      host: localhost  # Redis 서버 주소
      port: 6379       # 기본 포트


  # JPA
  jpa:
    open-in-view: true
    hibernate:
      # update : 빌드할 때마다 새로 만들기.
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # DB 컬럼명 snake 케이스로 교체
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


  # MySql
  # PORT 수정. 3306
  # testschema => 내 테이블 이름
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/virtudy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root1234
