websocket:
  port: ${SOCKET_PORT}

spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: host.docker.internal  # Redis 서버 주소
      port: ${REDIS_PORT}       # 기본 포트
      password: ${DEV_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DEV_DB_HOST:127.0.0.1}:${DEV_DB_PORT:3306}/${DEV_DB_NAME:virtudy}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

server:
  port: ${SERVER_PORT}


# [수정] 우리가 만든 KakaoClient가 사용할 커스텀 설정
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  # 프론트엔드에서 인가 코드를 받을 때 사용한 주소와 100% 일치해야 함
  # (보통 프론트엔드 라우터 주소)
  redirect-uri: "http://localhost:3030/login/callback/kakao"
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"

# JWT
jwt:
  secret_key: ${JWT_SECRET_KEY}
  access-expmin: ${JWT_ACCESS_EXPMIN}    # 30분
  refresh-expmin: ${JWT_REFRESH_EXPMIN} # 2주로 처리
